### ISSUE TITLE
Please add a option for the private key 

### ISSUE THREAD

**Issue by PedroGomes** [joshdick/pytograph#1]
I'm trying to use this but it gives me an error about a bad DSA key. I have multiple keys for identification in different servers and this was never an issue except for pysftp it seems (even I created my own DSA pair). I went to your script and using the pysftp.Connection(host, username = username,private_key ="blah/blah/key") I made it work so I was hopping you could add this parameter to the config file.

**Comment by joshdick** [comment]
Thanks for that idea! :-)

Implemented as of 06efb9752f9c0e49e0ba0f7e905463d06515b29a.
