### ISSUE TITLE
"IOError: [Errno 24] Too many open files" when launched via launchd

### ISSUE THREAD

**Issue by tjluoma** [joshdick/pytograph#2]
`/usr/local/pytograph/pytograph -c /usr/local/pytograph/pytograph.cfg`

works fine on the command line, but in launchd I get:

```
INFO: Path mapping initializing:
Changes at local path
    /Users/luomat/Dropbox/Public/Dreamhost/f.luo.ma
will be reflected at remote path
    luomat@iceman.dreamhost.com:/home/luomat/f.luo.ma
INFO: Path mapping initializing:
Changes at local path
    /Users/luomat/Dropbox/Public/Dreamhost/images.luo.ma
will be reflected at remote path
    luomat@iceman.dreamhost.com:/home/luomat/images.luo.ma
INFO: Path mapping initializing:
Changes at local path
    /Users/luomat/Dropbox/Public/Dreamhost/notes.luo.ma
will be reflected at remote path
    luomat@iceman.dreamhost.com:/home/luomat/notes.luo.ma
Traceback (most recent call last):
  File "/usr/local/pytograph/pytograph", line 248, in <module>
  File "/usr/local/pytograph/pytograph", line 230, in _main
  File "/Library/Python/2.7/site-packages/watchdog/observers/api.py", line 357, in schedule
  File "/Library/Python/2.7/site-packages/watchdog/observers/kqueue.py", line 445, in __init__
IOError: [Errno 24] Too many open files
```

here's my 'com.tjluoma.pytograph.plist' file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>AbandonProcessGroup</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>com.tjluoma.pytograph</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/pytograph/pytograph</string>
        <string>--config-file</string>
        <string>/usr/local/pytograph/pytograph.cfg</string>
    </array>
    <key>StandardErrorPath</key>
    <string>/Users/luomat/Library/Logs/pytograph.log</string>
    <key>StandardOutPath</key>
    <string>/Users/luomat/Library/Logs/pytograph.log</string>
</dict>
</plist>
```

Any ideas why it fails in launchd? Seems like that would be an ideal way to run it.

**Comment by joshdick** [comment]
On Mac OS X, launchd has limits on the allowed number of open files that are independent of those allowed for a normal shell (and can be configured independently.) You can see the current configuration by running `launchctl limit`. Here's the output on my Mac OS X Lion system:

```
cpu         unlimited      unlimited      
filesize    unlimited      unlimited      
data        unlimited      unlimited      
stack       8388608        67104768       
core        0              unlimited      
rss         unlimited      unlimited      
memlock     unlimited      unlimited      
maxproc     709            1064           
maxfiles    256            unlimited    
```

If your system is configured similarly, maxfiles = 256 may not be large enough to accomodate the folder(s) you're attempting to monitor with pytograph. The two values "256" and "unlimited" are "soft" and "hard" limits respectively, according to the launchctl manpage. That manpage refers to the manpage setrlimit(2), which explains what soft and hard limits are:

"A resource limit is specified as a soft limit and a hard limit. When a soft limit is exceeded a process may receive a signal (for example, if the cpu time or file size is exceeded), but it will be allowed to continue execution until it reaches the hard limit (or modifies its resource limit)."

So it looks like the filesystem monitoring library used by pytograph (called watchdog) may be hitting the configured soft limit for launchctl and triggering an IOError, so there's nothing I can change in my code to solve the problem.

However, it looks like the limits are configurable, so you can try experimenting with different values (I haven't, so no guarantees.) Try changing the soft limit by running `launchctl limit maxfiles 400000` and see if that fixes the problem inside a running session. If it does, you can permanently configure the soft limit by adding the line `limit maxfiles 400000` to /etc/launchd.conf. (Source: http://artur.hefczyc.net/node/27)

All of that said, I don't recommend running pytograph via launchd but rather in an interactive session. If pytograph does something unexpected, you'd never be able to tell if you were running it via launchd. For example, it would be hard to notice a Git operation that causes unintended deletes on the remote server unless you were running pytograph interactively.

**Comment by tjluoma** [comment]
On Mar 11, 2012, at 10:30 AM, Josh Dick
reply@reply.github.com
wrote:

> If your system is configured similarly, maxfiles = 256 may not be large enough to accomodate the folder(s) you're attempting to monitor with pytograph. The two values "256" and "unlimited" are "soft" and "hard" limits respectively, according to the launchctl manpage. That manpage refers to the manpage setrlimit(2), which explains what soft and hard limits are:

Of course! I had a vague memory of such a thing but had forgotten how
to check it

> All of that said, I don't recommend running pytograph via launchd but rather in an interactive session. If pytograph does something unexpected, you'd never be able to tell if you were running it via launchd. For example, it would be hard to notice a Git operation that causes unintended deletes on the remote server unless you were running pytograph interactively.

My idea is to make launchd send the output to a file that I can track
using Console.app. I'll try that.

Thanks again

TjL

**Comment by joshdick** [comment]
No problem! :)
